import { describe, test, expect } from 'vitest';
import { hashData, verifyHashedData } from './index.js';


/* ************************************************************************************************
 *                                         IMPLEMENTATION                                         *
 ************************************************************************************************ */

describe('Data Hashing', () => {
  test.each([
    ['n18R%r7e7#EBTymabc'],
    ['n18R%r7e7#EBTymW![~A2#&0y4CVf*yM1UW?YilSu(Vc^g-u_gN3QG7G^9./0~FD8a@c0O(V*?|abc'],
    ['2.6C*/;uXVe,U_X0V(6/2zq_d<ZP@1mn0~O3G?N5ev(Rc;/j]VO998|6FN%aYI57sBs9WD;v,ruUS>_u_-H)y7d|G+jRCh4d:mZ9rJVP8B|F8Kruum<B|wHG7I7b[w;:Ta8+1@TNxkK*N&LXi%td-eT9OaJq6dJ54V:ba+alS<WBdXm6Q!Cfe<hOD8i|d!T~lEK.@@MuAc5~Bt9A~u@xk>McMX8fT8ff&c0#j[2eH;RrB9ux8Fu.taBsruiip*/tK_<3:T]_2x;BMB%(iQxIDYi__Sc]Y#d]Fa^7yLABs]w,-;?aMeap)6QkfY@e]JaiF5S.Hk.+cG%rx;FPZVG0;jTle0o)7%U^-hLP|yq*v0t1~sCSvH<zo&3l1%.9r73Nk|%V&TVzXLI%ldN1(7S;YFQ)@5rtOU?Z95Zj5j2!9Hq&;yAV:%Eu>^t::|NKJtX,BjB|#5GE9Ng()JteErb!xa<lx^A1<(WHaL+phv_3PZzg?@89(Byrxf)ZMgaF:5W,HDa[HYe:iGYD,@cC#mm4VE/bCuGhc*WWrL?EFY.:D-ff!5Q[~:xdmg|;J:lKhPGXwXA^~_;6Mp*ToLhA_@lwO-%Cr_WOKD?X^xzT>dqzU^P4nt!3^fd)H(n6zndIaq(t)@6BI!yp+^[R^b^<KibFpJq:JbEott:-w&qKWPK)ocSL7!BwBvWy1~2wR%HX9Wo?ytKaU<gB!o,C%Z^4zBf),uEE?FbtqmGa,YLYhYN2:~#,/ECAhkgl]hHnL|/(!(|W>>@Hdrt,4UxFyB)zt;jUnF;Mr71xy8Tcb?IbA.4!~+s6nK-cW@D]^uVQIqFA!EV73mK/i@Llwv3w#&yZjSs@ZolIL^XWZAqMAVMr&kCJA>40j,dt:a-wrLd]YtBmj4R2vA&NQAW8l:#<vtjY5lXZArU)Vf-86Vh8NRs<u++gH<?(!/AxC1El^w;hGfR?(+sAG2D#|IqH<hPiYbS[Ch0j*DIAmO9&q6r(?,zoyMvMmlRssN,niXw@9DEwbT0v)L/gkvv,m2a/jaD~eD;(*FzGf::O!j4su:M4@]HVR<!0lpks)[s6Zvfl<.Xdd&aiBJ-XTKh!6_H368y>eUk#0]RE]F_*7eaQf?)Eogi;:DkSsF@O%%-[FUM<ZM_,|^Cu>aWF~#ena4;B&;l~;(P?2sG82l2x<m*eh4ti,4_dvk,MMz-^xI789L3+J~o%[QxmABjVHLqdDJA[^^+A@)THp9Z(:Qfq/lJ~z>(15.V?[m?@RUVmxJKUnXUwrGXR[23k3CzF(]eu~i?H?;rLpLRPSS..TmVgL7lnOtm*,qmaL58h*(:XlJe21o/ih/TZPpl1O(1?^jDOUDY3vwE@k.H]3fffJ28lQn/F%pO<G&RNEesYqUi~*j^:ld?e3LJ5x9w7MfsHurb6~CqMoHy)tiW);qHwvVv/6AcTJQ<ZaE*h[atW0MiZQ*R~9^Z-fj>s9cI:~|Sgeq|VM/Y~ixyT0O+/I9CNny4pvqM|id/nQq-l/uIzR3L0+!eeCO|h2WKRIH4|gc/Z,*M#|u|e|r2F4/t2(tX^L.BD<vUiQ/+;AlXTNcLNHmI@wp,*]02vD;bj-+~!FV<&-N,y|:I[prlvYK4frGroCZ4*,v8A>z8y[0p,ggGDV_)R?dxZ:9iTEj?Q.^^5F6x-]:DCkT629<RUQi+d:M?V~)oikRwXE>YeI*!@97Pe1#N*qwva+|wb~KA|D.zsPQjr2q;I%-XR*(Bs@M6uT7WE5h1<yo!.)<rJY.)iC|[J3vjd0SW&8M*SC;~7ytB|gCsp&sXA_[*9wuwZ0)If^hp0z2ojKO*W_]pR&~FKVcd^j@yg2QNA?_Shlu0JByK2ZDIIXT45_B.?y8QUO/?Wx3%*u[4d,9<0~u,S|xJ5cZ0[q6Q.<^XWZOM6yryowfj^k7)chU9qLp&Dyp?m5)Jf<od5HFzt)4s;Vp7W8wf|Y|^DilLF~es[+&RBer|BzvC7SYcz9(lc/[%n]kQxu)&BLP*fbdybh*iXaaLL4S-7:s_0c#;Fq9dboVILzE]N-nQ!&ELoabc'],
  ])('Can hash and verify strings of any length', async (a) => {
    const hash = await hashData(a);
    expect(hash).toBeTypeOf('string');
    expect(hash.length).toBeGreaterThan(0);
    await expect(verifyHashedData(hash, a)).resolves.toBe(true);
  });

  test('cannot verify a string that doesn\'t match', async () => {
    const PASS_1 = '2.6C*/;uXVe,U_X0V(6/2zq_d<ZP@1mn0~O3G?N5ev(Rc;/j]VO998|6FN%aYI57sBs9WD;v,ruUS>_u_-H)y7d|G+jRCh4d:mZ9rJVP8B|F8Kruum<B|wHG7I7b[w;:Ta8+1@TNxkK*N&LXi%td-eT9OaJq6dJ54V:ba+alS<WBdXm6Q!Cfe<hOD8i|d!T~lEK.@@MuAc5~Bt9A~u@xk>McMX8fT8ff&c0#j[2eH;RrB9ux8Fu.taBsruiip*/tK_<3:T]_2x;BMB%(iQxIDYi__Sc]Y#d]Fa^7yLABs]w,-;?aMeap)6QkfY@e]JaiF5S.Hk.+cG%rx;FPZVG0;jTle0o)7%U^-hLP|yq*v0t1~sCSvH<zo&3l1%.9r73Nk|%V&TVzXLI%ldN1(7S;YFQ)@5rtOU?Z95Zj5j2!9Hq&;yAV:%Eu>^t::|NKJtX,BjB|#5GE9Ng()JteErb!xa<lx^A1<(WHaL+phv_3PZzg?@89(Byrxf)ZMgaF:5W,HDa[HYe:iGYD,@cC#mm4VE/bCuGhc*WWrL?EFY.:D-ff!5Q[~:xdmg|;J:lKhPGXwXA^~_;6Mp*ToLhA_@lwO-%Cr_WOKD?X^xzT>dqzU^P4nt!3^fd)H(n6zndIaq(t)@6BI!yp+^[R^b^<KibFpJq:JbEott:-w&qKWPK)ocSL7!BwBvWy1~2wR%HX9Wo?ytKaU<gB!o,C%Z^4zBf),uEE?FbtqmGa,YLYhYN2:~#,/ECAhkgl]hHnL|/(!(|W>>@Hdrt,4UxFyB)zt;jUnF;Mr71xy8Tcb?IbA.4!~+s6nK-cW@D]^uVQIqFA!EV73mK/i@Llwv3w#&yZjSs@ZolIL^XWZAqMAVMr&kCJA>40j,dt:a-wrLd]YtBmj4R2vA&NQAW8l:#<vtjY5lXZArU)Vf-86Vh8NRs<u++gH<?(!/AxC1El^w;hGfR?(+sAG2D#|IqH<hPiYbS[Ch0j*DIAmO9&q6r(?,zoyMvMmlRssN,niXw@9DEwbT0v)L/gkvv,m2a/jaD~eD;(*FzGf::O!j4su:M4@]HVR<!0lpks)[s6Zvfl<.Xdd&aiBJ-XTKh!6_H368y>eUk#0]RE]F_*7eaQf?)Eogi;:DkSsF@O%%-[FUM<ZM_,|^Cu>aWF~#ena4;B&;l~;(P?2sG82l2x<m*eh4ti,4_dvk,MMz-^xI789L3+J~o%[QxmABjVHLqdDJA[^^+A@)THp9Z(:Qfq/lJ~z>(15.V?[m?@RUVmxJKUnXUwrGXR[23k3CzF(]eu~i?H?;rLpLRPSS..TmVgL7lnOtm*,qmaL58h*(:XlJe21o/ih/TZPpl1O(1?^jDOUDY3vwE@k.H]3fffJ28lQn/F%pO<G&RNEesYqUi~*j^:ld?e3LJ5x9w7MfsHurb6~CqMoHy)tiW);qHwvVv/6AcTJQ<ZaE*h[atW0MiZQ*R~9^Z-fj>s9cI:~|Sgeq|VM/Y~ixyT0O+/I9CNny4pvqM|id/nQq-l/uIzR3L0+!eeCO|h2WKRIH4|gc/Z,*M#|u|e|r2F4/t2(tX^L.BD<vUiQ/+;AlXTNcLNHmI@wp,*]02vD;bj-+~!FV<&-N,y|:I[prlvYK4frGroCZ4*,v8A>z8y[0p,ggGDV_)R?dxZ:9iTEj?Q.^^5F6x-]:DCkT629<RUQi+d:M?V~)oikRwXE>YeI*!@97Pe1#N*qwva+|wb~KA|D.zsPQjr2q;I%-XR*(Bs@M6uT7WE5h1<yo!.)<rJY.)iC|[J3vjd0SW&8M*SC;~7ytB|gCsp&sXA_[*9wuwZ0)If^hp0z2ojKO*W_]pR&~FKVcd^j@yg2QNA?_Shlu0JByK2ZDIIXT45_B.?y8QUO/?Wx3%*u[4d,9<0~u,S|xJ5cZ0[q6Q.<^XWZOM6yryowfj^k7)chU9qLp&Dyp?m5)Jf<od5HFzt)4s;Vp7W8wf|Y|^DilLF~es[+&RBer|BzvC7SYcz9(lc/[%n]kQxu)&BLP*fbdybh*iXaaLL4S-7:s_0c#;Fq9dboVILzE]N-nQ!&ELo';
    const PASS_2 = '2.6C*/;uXVe,U_X0V(6/2zq_d<ZP@1mn0~O3G?N5ev(Rc;/j]VO998|6FN%aYI57sBs9WD;v,ruUS>_u_-H)y7d|G+jRCh4d:mZ9rJVP8B|F8Kruum<B|wHG7I7b[w;:Ta8+1@TNxkK*N&LXi%td-eT9OaJq6dJ54V:ba+alS<WBdXm6Q!Cfe<hOD8i|d!T~lEK.@@MuAc5~Bt9A~u@xk>McMX8fT8ff&c0#j[2eH;RrB9ux8Fu.taBsruiip*/tK_<3:T]_2x;BMB%(iQxIDYi__Sc]Y#d]Fa^7yLABs]w,-;?aMeap)6QkfY@e]JaiF5S.Hk.+cG%rx;FPZVG0;jTle0o)7%U^-hLP|yq*v0t1~sCSvH<zo&3l1%.9r73Nk|%V&TVzXLI%ldN1(7S;YFQ)@5rtOU?Z95Zj5j2!9Hq&;yAV:%Eu>^t::|NKJtX,BjB|#5GE9Ng()JteErb!xa<lx^A1<(WHaL+phv_3PZzg?@89(Byrxf)ZMgaF:5W,HDa[HYe:iGYD,@cC#mm4VE/bCuGhc*WWrL?EFY.:D-ff!5Q[~:xdmg|;J:lKhPGXwXA^~_;6Mp*ToLhA_@lwO-%Cr_WOKD?X^xzT>dqzU^P4nt!3^fd)H(n6zndIaq(t)@6BI!yp+^[R^b^<KibFpJq:JbEott:-w&qKWPK)ocSL7!BwBvWy1~2wR%HX9Wo?ytKaU<gB!o,C%Z^4zBf),uEE?FbtqmGa,YLYhYN2:~#,/ECAhkgl]hHnL|/(!(|W>>@Hdrt,4UxFyB)zt;jUnF;Mr71xy8Tcb?IbA.4!~+s6nK-cW@D]^uVQIqFA!EV73mK/i@Llwv3w#&yZjSs@ZolIL^XWZAqMAVMr&kCJA>40j,dt:a-wrLd]YtBmj4R2vA&NQAW8l:#<vtjY5lXZArU)Vf-86Vh8NRs<u++gH<?(!/AxC1El^w;hGfR?(+sAG2D#|IqH<hPiYbS[Ch0j*DIAmO9&q6r(?,zoyMvMmlRssN,niXw@9DEwbT0v)L/gkvv,m2a/jaD~eD;(*FzGf::O!j4su:M4@]HVR<!0lpks)[s6Zvfl<.Xdd&aiBJ-XTKh!6_H368y>eUk#0]RE]F_*7eaQf?)Eogi;:DkSsF@O%%-[FUM<ZM_,|^Cu>aWF~#ena4;B&;l~;(P?2sG82l2x<m*eh4ti,4_dvk,MMz-^xI789L3+J~o%[QxmABjVHLqdDJA[^^+A@)THp9Z(:Qfq/lJ~z>(15.V?[m?@RUVmxJKUnXUwrGXR[23k3CzF(]eu~i?H?;rLpLRPSS..TmVgL7lnOtm*,qmaL58h*(:XlJe21o/ih/TZPpl1O(1?^jDOUDY3vwE@k.H]3fffJ28lQn/F%pO<G&RNEesYqUi~*j^:ld?e3LJ5x9w7MfsHurb6~CqMoHy)tiW);qHwvVv/6AcTJQ<ZaE*h[atW0MiZQ*R~9^Z-fj>s9cI:~|Sgeq|VM/Y~ixyT0O+/I9CNny4pvqM|id/nQq-l/uIzR3L0+!eeCO|h2WKRIH4|gc/Z,*M#|u|e|r2F4/t2(tX^L.BD<vUiQ/+;AlXTNcLNHmI@wp,*]02vD;bj-+~!FV<&-N,y|:I[prlvYK4frGroCZ4*,v8A>z8y[0p,ggGDV_)R?dxZ:9iTEj?Q.^^5F6x-]:DCkT629<RUQi+d:M?V~)oikRwXE>YeI*!@97Pe1#N*qwva+|wb~KA|D.zsPQjr2q;I%-XR*(Bs@M6uT7WE5h1<yo!.)<rJY.)iC|[J3vjd0SW&8M*SC;~7ytB|gCsp&sXA_[*9wuwZ0)If^hp0z2ojKO*W_]pR&~FKVcd^j@yg2QNA?_Shlu0JByK2ZDIIXT45_B.?y8QUO/?Wx3%*u[4d,9<0~u,S|xJ5cZ0[q6Q.<^XWZOM6yryowfj^k7)chU9qLp&Dyp?m5)Jf<od5HFzt)4s;Vp7W8wf|Y|^DilLF~es[+&RBer|BzvC7SYcz9(lc/[%n]kQxu)&BLP*fbdybh*iXaaLL4S-7:s_0c#;Fq9dboVILzE]N-nQ!&ELoabc';
    const hash1 = await hashData(PASS_1);
    await expect(verifyHashedData(hash1, PASS_1)).resolves.toBe(true);
    await expect(verifyHashedData(hash1, PASS_2)).resolves.toBe(false);
  });
});
