import { Buffer } from 'node:buffer';
import argon2 from 'argon2';
import { ENVIRONMENT } from '../environment/index.js';

/* ************************************************************************************************
 *                                         IMPLEMENTATION                                         *
 ************************************************************************************************ */

/**
 * Hashes a given string and makes use of the hashing secret to enhance the security of the result.
 * @param data
 * @returns Promise<string>
 */
const hashData = (data: string): Promise<string> => argon2.hash(data, {
  type: argon2.argon2id,
  secret: Buffer.from(ENVIRONMENT.HASHING_SECRET),
});

/**
 * Verifies if the data string matches a hash previously generated by this hashing module.
 * @param dataHash
 * @param data
 * @returns Promise<boolean>
 */
const verifyHashedData = (dataHash: string, data: string): Promise<boolean> => (
  argon2.verify(dataHash, data, {
    secret: Buffer.from(ENVIRONMENT.HASHING_SECRET),
  })
);





/* ************************************************************************************************
 *                                         MODULE EXPORTS                                         *
 ************************************************************************************************ */
export {
  hashData,
  verifyHashedData,
};
